name: daily e2e tests

on:
  push:
    branches:
      - harvey-add-karura-test
	#schedule:
	  #- cron: '*/5 * * * *' #Test every 5 mins or on push
  
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: v0.10.0
    - uses: actions/checkout@v2
    - name: Test
      run: |
        yarn install
        echo "Daily Test is now running..."
        yarn test:init-e2e-tests  #Should test on all available networks
